package entities;
// Generated Nov 19, 2019 12:16:18 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "MyShop")
public class Orders implements java.io.Serializable {

	private long orderId;
	private String customerUsername;
	private long orderAmount;
	private int orderStatus;
	private Date orderDate;
	private int orderNumber;

	public Orders() {
	}

	public Orders(long orderId, String customerUsername, long orderAmount, int orderStatus, Date orderDate,
			int orderNumber) {
		this.orderId = orderId;
		this.customerUsername = customerUsername;
		this.orderAmount = orderAmount;
		this.orderStatus = orderStatus;
		this.orderDate = orderDate;
		this.orderNumber = orderNumber;
	}

	@Id

	@Column(name = "order_id", unique = true, nullable = false)
	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "customer_username", nullable = false)
	public String getCustomerUsername() {
		return this.customerUsername;
	}

	public void setCustomerUsername(String customerUsername) {
		this.customerUsername = customerUsername;
	}

	@Column(name = "order_amount", nullable = false, precision = 10, scale = 0)
	public long getOrderAmount() {
		return this.orderAmount;
	}

	public void setOrderAmount(long orderAmount) {
		this.orderAmount = orderAmount;
	}

	@Column(name = "order_status", nullable = false)
	public int getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(int orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "order_date", nullable = false, length = 10)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "order_number", nullable = false)
	public int getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(int orderNumber) {
		this.orderNumber = orderNumber;
	}

}
