package entities;
// Generated Nov 19, 2019 12:16:18 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Orderdetails generated by hbm2java
 */
@Entity
@Table(name = "orderdetails", catalog = "MyShop")
public class Orderdetails implements java.io.Serializable {

	private long orderdetailId;
	private long productId;
	private long orderId;
	private long orderdetailPrice;
	private int orderdetailQuantity;

	public Orderdetails() {
	}

	public Orderdetails(long orderdetailId, long productId, long orderId, long orderdetailPrice,
			int orderdetailQuantity) {
		this.orderdetailId = orderdetailId;
		this.productId = productId;
		this.orderId = orderId;
		this.orderdetailPrice = orderdetailPrice;
		this.orderdetailQuantity = orderdetailQuantity;
	}

	@Id

	@Column(name = "orderdetail_id", unique = true, nullable = false)
	public long getOrderdetailId() {
		return this.orderdetailId;
	}

	public void setOrderdetailId(long orderdetailId) {
		this.orderdetailId = orderdetailId;
	}

	@Column(name = "product_id", nullable = false)
	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	@Column(name = "order_id", nullable = false)
	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "orderdetail_price", nullable = false, precision = 10, scale = 0)
	public long getOrderdetailPrice() {
		return this.orderdetailPrice;
	}

	public void setOrderdetailPrice(long orderdetailPrice) {
		this.orderdetailPrice = orderdetailPrice;
	}

	@Column(name = "orderdetail_quantity", nullable = false)
	public int getOrderdetailQuantity() {
		return this.orderdetailQuantity;
	}

	public void setOrderdetailQuantity(int orderdetailQuantity) {
		this.orderdetailQuantity = orderdetailQuantity;
	}

}
