package entities;
// Generated Nov 19, 2019 12:16:18 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "products", catalog = "MyShop", uniqueConstraints = @UniqueConstraint(columnNames = "product_name"))
public class Products implements java.io.Serializable {

	private long productId;
	private int categoryId;
	private String productDescription;
	private String productName;
	private String productImage;
	private long productPrice;
	private String productDetail;

	public Products() {
	}

	public Products(long productId, int categoryId, String productDescription, String productName, String productImage,
			long productPrice, String productDetail) {
		this.productId = productId;
		this.categoryId = categoryId;
		this.productDescription = productDescription;
		this.productName = productName;
		this.productImage = productImage;
		this.productPrice = productPrice;
		this.productDetail = productDetail;
	}

	@Id

	@Column(name = "product_id", unique = true, nullable = false)
	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	@Column(name = "category_id", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "product_description", nullable = false)
	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	@Column(name = "product_name", unique = true, nullable = false)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "product_image", nullable = false)
	public String getProductImage() {
		return this.productImage;
	}

	public void setProductImage(String productImage) {
		this.productImage = productImage;
	}

	@Column(name = "product_price", nullable = false, precision = 10, scale = 0)
	public long getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(long productPrice) {
		this.productPrice = productPrice;
	}

	@Column(name = "product_detail", nullable = false, length = 65535)
	public String getProductDetail() {
		return this.productDetail;
	}

	public void setProductDetail(String productDetail) {
		this.productDetail = productDetail;
	}

}
